FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci --only=production

COPY services/product ./services/product
COPY services/shared ./services/shared

EXPOSE 8081

CMD ["node", "services/product/product-service.js"]
